listdata=list("AB","CD","EF","GH")
print(listdata)
names(listdata)=c("First","Second","Third","Fourth")
print(listdata)
li=c("IJ")
m=append(listdata,li)
print("Element added at last:")
print(m)
n=head(m,-1)
print("Last element deleted:")
print(n)
n[3]="PQ"
print("3rd element updated:")
print(n)
